### ISSUE TITLE
SNSへのシェアボタンを設置

### ISSUE THREAD

**Issue by iyuto** [OthloTech/OthloHackathon#7]
参加申し込み前と後の二種類のシェアボタンを設置したい。
- サイトの上下部二箇所くらいハッカソンイベント自体のシェアボタン
- Googleフォーム送信後の「ハッカソンの参加を申込みました」をシェアできるリンク

ハッシュタグは#othlohackかな？

**Comment by pokohide** [comment]
## OGPタグ追加(twitter, facebook)

OGPタグはサイトをシェアするときの説明文や画像を設定するタグ

参考
https://ferret-plus.com/610
